### ISSUE TITLE
stylelint-order

### ISSUE THREAD

**Issue by illycz** [machal/example-css-architecture#2]
Ahoj Martine,
nepřemýšlel jsi o zařazení pluginu, který řeší řazení?

Mám ho implementovaný, ale nedokázal jsem se rozhodnout, které z řazení vybrat. Nakonec jsem zvolil konfiguraci VisionApps: https://github.com/visionappscz/stylelint-config-visionapps-order.

Co si o tom myslíš? :)

**Comment by machal** [comment]
Ahoj, je to v plánu přesně s tímhle Adamovým nástrojem. Díky za otevření. ;)

**Comment by machal** [comment]
Closed with https://github.com/machal/example-css-architecture/commit/76c38969b314eaf9dedf9db2e74e483ac3c05a6c
